@baseUrl = http://localhost:8080
@emailId = 4b94413a-52a5-4dcf-b89b-a71078225531

### Health
GET {{baseUrl}}/health

### List emails
GET {{baseUrl}}/api/emails

### Get email
GET {{baseUrl}}/api/emails/{{emailId}}
